### ISSUE TITLE
Error occurred on build

### ISSUE THREAD

**Issue by afrokick** [Meteor-Community-Packages/meteor-typescript#5]
Version 0.3.2
Meteor 1.12

Any idea why it appears?

```
/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null
    at Hash.update (internal/crypto/hash.js:82:11)
    at /Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/watch.ts:329:28
    at Array.forEach (<anonymous>)
    at /Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/watch.ts:329:8
    at profileWrapper (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:265:16)
    at JsOutputResource._get (/tools/isobuild/compiler-plugin.js:982:19)
    at JsOutputResource.get hash [as hash] (/tools/isobuild/compiler-plugin.js:945:28)
    at ImportScanner.findImportedModuleIdentifiers (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:979:39)
    at ImportScanner.profileWrapper (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:265:16)
    at ImportScanner.scanFile (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1092:37)
    at /Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at _.each._.forEach (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at ImportScanner.scanFile (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:740:14
    at Array.forEach (<anonymous>)
    at ImportScanner.scanImports (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:738:22)
    at ImportScanner.profileWrapper (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:265:16)
    at /tools/isobuild/compiler-plugin.js:1360:17
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1325:19)
    at Function.profileWrapper (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:265:16)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1137:8)
    at ClientTarget.profileWrapper (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:265:16)
    at /tools/isobuild/bundler.js:856:12
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:844:18)
    at ClientTarget.profileWrapper (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:265:16)
    at /tools/isobuild/bundler.js:3188:14
    at profileWrapper (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:265:16)
    at /tools/isobuild/bundler.js:3340:25
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3294:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3169:31)
    at /tools/isobuild/bundler.js:3113:32
    at Slot.withValue (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.js:73:29)
    at Object.withCache (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1659:39)
    at Object.<anonymous> (/tools/isobuild/bundler.js:3113:16)
    at Object.profileWrapper [as bundle] (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:265:16)
    at /tools/runners/run-app.js:572:24
    at profileWrapper (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:265:16)
    at time (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:284:12)
    at Function.run (/Users/xxx/.meteor/packages/meteor-tool/.1.12.0.1cubtib.nojol++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:303:14)
    at bundleApp (/tools/runners/run-app.js:571:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:617:35)
    at AppRunner._fiber (/tools/runners/run-app.js:931:28)
    at /tools/runners/run-app.js:401:12 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by perbergland** [comment]
There’s nothing in the stack trace that looks familiar. Please try running the build process in a debugger and set a conditional breakpoint on the offending line to backtrace and find out why you get a null passed down.

IIRC you just set NODE_OPTIONS to include --inspect or --inspect-brk, like NODEOPTIONS="--inspect" meteor build ... but it’s been a while…

**Comment by perbergland** [comment]
closing due to inactivity
